language: android

android:
  components:
  - android-29
  - build-tools-29.0.1
  - extra-android-m2repository
  - extra-google-m2repository
  - platform-tools
  - tools

jdk:
- oraclejdk8

script:
- ./gradlew test

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.m2
